### ISSUE TITLE
MacOS malware protection

### ISSUE THREAD

**Issue by rubenphilipp** [cac-t-u-s/om-sharp-users#69] opened 2022-09-17 21:42 UTC
Hello Jean,

I just installed OM# on my Mac (running MacOS 12.5.1). It seems as if the OS classifies the program as "malware" since the recently built-in malware automatism hits on the application and prevents it from being executes as long as the user doesn't manually (via the information panel in the Finder) disables the malware protection. I have no clue why it is this way. Anyhow, I'd suggest to have a look at this issue at the next build/release. 
Enclosed are two screenshots illustrating the message at launch and the option proposed in the Information window. Since my system is in German, I beg your pardon for having to "guess-translate".

<img width="465" alt="Bildschirmfoto 2022-09-17 um 23 41 28" src="https://user-images.githubusercontent.com/12574070/190877261-c1677e37-b3e7-4746-ab92-49c72e350f5c.png">

<img width="377" alt="Bildschirmfoto 2022-09-17 um 23 41 42" src="https://user-images.githubusercontent.com/12574070/190877267-b6fa460d-05b4-43eb-8b38-950688cb1155.png">

Best regards
Ruben

**Comment by j-bresson** [comment] 2022-09-17 22:35
Hi Ruben, thanks for the report. I'm transferring it to th `om-sharp-users` issues.
This is (unfortunately) a known issue (see https://github.com/cac-t-u-s/om-sharp-users/issues/68).
om# 1.7 is not signed as it should be. You can use v1.6 until the problem is solved.
All best

**Comment by rubenphilipp** [comment] 2022-09-18 08:43
Thanks for the quick reply. That makes sense. I searched, but didn't find #68. 

Best regards
Ruben

**Comment by rubenphilipp** [comment] 2022-09-21 09:28
Hey Jean,

thanks for working it out. The now updated version runs flawlessly.

Regards
Ruben

**Closed** 2022-09-21 09:29 UTC
